name: S3 Sandbox Cleanup
description: A GitHub action to delete S3 sandbox releases that do not exist in Git as branches.
branding:
  icon: check-circle
  color: green
inputs:
  s3Path:
    description: The S3 Bucket with s3:// protocol prefix
    required: true

runs:
  using: 'composite'
  steps:

      - name: Clean up S3 path
        run: |
          git ls-remote | grep -o 'releases/sandbox/.*' | sed 's|releases/sandbox/||g' | tee sandbox-tags.txt
          for release in $(aws s3 ls $INPUT_S3PATH/releases/sandbox/ | awk '{print $2}' | sed 's|/||g')
          do
            if [[ -z "$(grep -E "^$release\$" sandbox-tags.txt)" ]]
            then
              echo "Deleting $INPUT_S3PATH/releases/sandbox/$release"
              # aws s3 rm $INPUT_S3PATH/releases/sandbox/$release
            fi
          done