name: S3 Sandbox Cleanup
description: A GitHub action to delete S3 sandbox releases that do not exist in Git as branches.
branding:
  icon: check-circle
  color: green
inputs:
  s3-path:
    description: The S3 Bucket with s3:// protocol prefix
    required: true

runs:
  using: 'composite'
  steps:
    - name: Clean up S3 path
      shell: bash
      run: |
        echo "S3 Path: ${{ inputs.s3-path }}"
        git ls-remote | (grep -o 'releases/sandbox/.*' || :) | sed 's|releases/sandbox/||g' | tee sandbox-tags.txt
        releaseTags=$(aws s3 ls ${{ inputs.s3-path }}/releases/sandbox/ | grep PRE | awk '{print $2}' | sed 's|/||g')
        echo "Release Tags:"
        echo $releaseTags
        IFS=$'\n'
        for release in $releaseTags
        do
          if [[ -z "$(grep -E "^$release\$" sandbox-tags.txt)" ]]
          then
            echo "Deleting ${{ inputs.s3-path }}/releases/sandbox/$release"
            aws s3 rm --recursive ${{ inputs.s3-path }}/releases/sandbox/$release
          fi
        done
        unset IFS